sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.11.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker build -t docker.parity -f .travis.dockerfile .
  - cd contract
  - docker build -t docker.contract .
