[network]
port = 30303
[rpc]
port = 8545
hosts = ["all"]
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "personal", "parity", "parity_accounts", "parity_set", "signer"]
[ui]
disable = true
[ipc]
disable = true
[dapps]
disable = true
[account]
password = ["/config/mach1.txt"]
[mining]
engine_signer = "0xa8a27df4c6de84e5cbe6c7301b56e090249225aa"