[network]
port = 30303
[rpc]
port = 8545
hosts = ["all"]
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "personal", "parity", "parity_accounts", "parity_set", "signer"]
[ui]
disable = true
[ipc]
disable = true
[dapps]
disable = true
[account]
password = ["/config/mach2.txt"]
[mining]
engine_signer = "0xec6f15a496467ba4006c9c3c18948e31c249e1a0"
reseal_on_txs = "none"